DefaultContentLanguage = "tr"
baseURL = "https://turankanbul.tech"
languageCode = "tr-TR"
paginate = 4
resourceDir = "resources"
summaryLength = 20
theme = "ryancv"
title = "Turan KANBUL - Software Developer"
[[menu.main]]
identifier = "contact"
name = "İletişim"
pre = "ion-at"
url = "#contact-card"
weight = 5
[menu.main.params]
builder = ["contact-info", "contact-form"]
[[menu.main]]
identifier = "blog"
name = "Blog"
pre = "ion-chatbox-working"
url = "#blog-card"
weight = 4
[menu.main.params]
builder = ["blog"]
[[menu.main]]
identifier = "works"
name = "Çalışmalar"
pre = "ion-paintbrush"
url = "#works-card"
weight = 3
[menu.main.params]
builder = ["portfolio"]
[[menu.main]]
identifier = "resume"
name = "Öz Geçmiş"
pre = "ion-android-list"
url = "#resume-card"
weight = 2
[menu.main.params]
builder = ["resume", "skills"]
[[menu.sidebar]]
identifier = "portfolio"
name = "Portfolio Page"
url = "/portfolio"
weight = 2
[[menu.sidebar]]
identifier = "blog"
name = "Blog Sayfası"
url = "/blog"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
authorName = "Turan KANBUL"
dateFormat = "January 2, 2006"
disqusComments = "your_disqus_shortname"
formspreeURL = "https://formspree.io/f/your_api_key"
googleAnalytics = ""
rtl = 0
skinColor = ""
skinDark = 0
skinMinimal = 0
[params.animation]
in = "fadeInLeft"
out = "fadeOutLeft"
[params.background]
type = "default"
[params.googleMaps]
key = "your_api_key"
lat = "40.773328"
long = "-73.960088"
zoom = "14"
[params.portfolio]
homeNumOfItems = 12
[[params.portfolio.filters]]
name = "Photo"
slug = "photo"
[[params.portfolio.filters]]
name = "Video"
slug = "video"
[[params.portfolio.filters]]
name = "Music"
slug = "music"
[[params.portfolio.filters]]
name = "Design"
slug = "design"
[params.sidebar]
categories = 1
enable = 1
latestPosts = 1
menuWidget = 1
search = 1
tags = 1
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
